### ISSUE TITLE
Credit to original FOIA author

### ISSUE THREAD

**Issue by NickvashKani** [wadefagen/datasets#25]
I thought it might be nice to credit the person responsible for getting this data released: 

https://austingwalters.com/university-of-illinois-urbana-champaign-grade-distributions/

Maybe include it in the readme?

**Comment by wadefagen** [comment]
The original motivation of the project was that dozens of my students were paying $20-$30 for access to public data through the "Easy-A" site, but did not release this data.

He declined to share it when one of my students asked. :(

When I approached the FOIA office for GPA records they had made public records, they didn't just give me a single year of data -- but all records they had released, dating back to 2010. My impression from the original FOIA was that this was a common request that was made before "Easy-A". No data that is provided in this repo was ever provided by "Easy-A" or anyone associated with it.

It would have been easier if the data was provided, and they would have been credited for providing the data had they provided it.
